"use client";
import {useEffect,useState} from "react";
import {db} from "../lib/db";
export type Brand={room_name:string;subtitle:string;logo_url:string;default_theme:"light"|"dark"};
export const DEFAULT_BRAND:Brand={room_name:"Dream Poker",subtitle:"DA NANG · RESERVATIONS",logo_url:"/dream-poker-logo.svg",default_theme:"dark"};
export default function BrandSettings({value,onSaved,lang="ko"}:{value:Brand;onSaved:(b:Brand)=>void;lang?:"ko"|"en"|"vi"}){
 const translations:Record<string,[string,string]>={"포커룸 브랜딩 · 화면 설정":["Room branding & appearance","Thương hiệu & giao diện"],"이 설정은 현재 연결된 예약 사이트 전체에 적용됩니다. 다른 포커룸을 동시에 운영하려면 예약 데이터와 도메인을 별도로 분리해야 합니다.":["These settings apply to the current reservation site. Separate data and domains are needed to operate multiple rooms simultaneously.","Cài đặt áp dụng cho trang đặt chỗ này. Cần tách dữ liệu và tên miền để vận hành nhiều phòng cùng lúc."],"포커룸 이름":["Poker room name","Tên phòng poker"],"상단 설명":["Header subtitle","Dòng phụ đầu trang"],"로고 이미지 URL (HTTPS 또는 /경로)":["Logo image URL (HTTPS or /path)","URL logo (HTTPS hoặc /đường-dẫn)"],"기본 테마":["Default theme","Giao diện mặc định"],"다크 모드":["Dark mode","Chế độ tối"],"라이트 모드":["Light mode","Chế độ sáng"],"설정 저장":["Save settings","Lưu cài đặt"],"설정이 저장됐습니다. 손님 화면에도 적용됩니다.":["Saved. Changes also apply to the guest site.","Đã lưu. Thay đổi cũng áp dụng cho trang khách."]};
 const tr=(k:string)=>lang==="ko"?k:translations[k]?.[lang==="en"?0:1]||k;
 const [draft,setDraft]=useState(value),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>setDraft(value),[value]);
 async function save(){if(!db)return;setBusy(true);const {error}=await db.rpc("update_reservation_brand",{p_name:draft.room_name,p_subtitle:draft.subtitle,p_logo:draft.logo_url,p_theme:draft.default_theme});setBusy(false);if(error)setNotice(error.message);else{onSaved(draft);setNotice(tr("설정이 저장됐습니다. 손님 화면에도 적용됩니다."))}}
 return <section className="panel brandSettings"><h2>{tr("포커룸 브랜딩 · 화면 설정")}</h2><p className="muted">{tr("이 설정은 현재 연결된 예약 사이트 전체에 적용됩니다. 다른 포커룸을 동시에 운영하려면 예약 데이터와 도메인을 별도로 분리해야 합니다.")}</p><div className="brandSettingsGrid"><label>{tr("포커룸 이름")}<input maxLength={70} value={draft.room_name} onChange={e=>setDraft({...draft,room_name:e.target.value})}/></label><label>{tr("상단 설명")}<input maxLength={120} value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})}/></label><label>{tr("로고 이미지 URL (HTTPS 또는 /경로)")}<input maxLength={500} value={draft.logo_url} onChange={e=>setDraft({...draft,logo_url:e.target.value})}/></label><label>{tr("기본 테마")}<select value={draft.default_theme} onChange={e=>setDraft({...draft,default_theme:e.target.value as "dark"|"light"})}><option value="dark">{tr("다크 모드")}</option><option value="light">{tr("라이트 모드")}</option></select></label></div><div className="brandPreview"><img src={draft.logo_url} alt="" onError={e=>{e.currentTarget.style.visibility="hidden"}}/><strong>{draft.room_name}</strong><small>{draft.subtitle}</small></div><button className="primary" disabled={busy} onClick={()=>void save()}>{tr("설정 저장")}</button>{notice&&<p role="status">{notice}</p>}</section>
}
