"use client";
import {useEffect,useState} from "react";
import {db} from "../lib/db";
type Profile={member_name:string;member_number:string};
export default function MemberBooking({language,gameId,arrival,onBooked}:{language:"ko"|"en"|"vi";gameId:string;arrival:string;onBooked:(token:string)=>void}){
 const [user,setUser]=useState<string|null>(null),[email,setEmail]=useState(""),[name,setName]=useState(""),[number,setNumber]=useState(""),[saved,setSaved]=useState<Profile|null>(null);
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const tr=language==="vi"?{login:"Đăng nhập bằng email",send:"Gửi liên kết đăng nhập",sent:"Kiểm tra email để đăng nhập.",save:"Lưu hồ sơ hội viên",name:"Tên tiếng Anh chính xác",number:"Mã hội viên",book:"Đặt chỗ bằng hồ sơ đã lưu",logout:"Đăng xuất",hint:"Mã hội viên do bạn nhập; thu ngân sẽ kiểm tra khi đến."}:language==="en"?{login:"Sign in with email",send:"Send sign-in link",sent:"Check your email for a sign-in link.",save:"Save member details",name:"Registered English name",number:"Member number",book:"One-tap booking with saved profile",logout:"Sign out",hint:"Membership number is self-entered and will be checked by the cashier."}:{login:"이메일로 간편 로그인",send:"로그인 링크 받기",sent:"이메일로 전송된 링크를 확인해주세요.",save:"회원정보 저장",name:"정확한 영문 회원 이름",number:"회원번호 (ID)",book:"저장된 정보로 한 번에 예약",logout:"로그아웃",hint:"입력한 회원번호는 캐셔가 확인하며, 계정만으로 회원번호가 인증되는 것은 아닙니다."};
 useEffect(()=>{if(!db)return;const client=db;let alive=true;async function init(){const {data}=await client.auth.getUser();const uid=data.user?.id||null;if(!alive)return;setUser(uid);if(uid){const r=await client.from("reservation_member_profiles").select("member_name,member_number").eq("user_id",uid).maybeSingle();if(alive){if(r.data){setSaved(r.data);setName(r.data.member_name);setNumber(r.data.member_number)}else setSaved(null)}}else setSaved(null)}
 void init();const {data:{subscription}}=client.auth.onAuthStateChange(()=>{void init()});return()=>{alive=false;subscription.unsubscribe()}},[]);
 async function otp(){if(!db||!email.trim())return;setBusy(true);const {error}=await db.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:window.location.origin}});setBusy(false);setNotice(error?.message||tr.sent)}
 async function save(){if(!db||!user)return;if(name.trim().length<2||number.trim().length<2){setNotice("이름과 회원번호를 확인해주세요.");return}setBusy(true);const {error}=await db.from("reservation_member_profiles").upsert({user_id:user,member_name:name.trim(),member_number:number.trim(),updated_at:new Date().toISOString()},{onConflict:"user_id"});setBusy(false);if(error)setNotice(error.message);else{setSaved({member_name:name.trim(),member_number:number.trim()});setNotice("저장되었습니다 / Saved")}}
 async function book(){if(!db||!user||!saved||!gameId)return;setBusy(true);const {data,error}=await db.rpc("request_member_poker_reservation",{p_game:gameId,p_arrival:new Date(arrival+"+07:00").toISOString()});setBusy(false);if(error)setNotice(error.message);else if(data?.[0]?.reservation_token){setNotice("예약 신청이 접수되었습니다. 캐셔 승인을 기다려주세요.");onBooked(String(data[0].reservation_token))}}
 return <div className="memberBox">{!user?<><p className="muted">{tr.login}</p><div className="memberLogin"><input type="email" autoComplete="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="primary" disabled={!email.trim()||busy} onClick={()=>void otp()}>{tr.send}</button></div></>:<><div className="memberAccount"><strong>{saved?("♠ "+saved.member_name+" · ID "+saved.member_number):tr.save}</strong><button className="outline" onClick={()=>void db?.auth.signOut()}>{tr.logout}</button></div><div className="memberFields"><label>{tr.name}<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name"/></label><label>{tr.number}<input value={number} onChange={e=>setNumber(e.target.value)} maxLength={40}/></label></div><p className="muted">{tr.hint}</p><div className="memberActions"><button className="outline" disabled={busy} onClick={()=>void save()}>{tr.save}</button><button className="primary" disabled={busy||!saved||!gameId||saved.member_name!==name.trim()||saved.member_number!==number.trim()} onClick={()=>void book()}>{tr.book} →</button></div></>}{notice&&<p className="memberNotice" role="status">{notice}</p>}</div>
}
