"use client";
import {useEffect,useMemo,useState} from "react";
type Lang="ko"|"en"|"vi";
type Status="pending"|"confirmed"|"waitlisted"|"rejected"|"checked_in";
type Booking={id:string;name:string;game:string;arrival:string;status:Status;createdAt:string};
const games=[{name:"3M TIME ATTACK",time:"11:00",seats:9},{name:"5M TIME ATTACK",time:"17:00",seats:9},{name:"10M TIME ATTACK",time:"19:00",seats:9}];
const dictionary={
 ko:{tag:"DA NANG · TABLE RESERVATION",heading:"포커 예약, 이제 직접 간편하게",sub:"원하는 게임과 도착 시간을 선택하세요.",demo:"데모 모드 · 실제 매장으로 예약이 전달되지 않습니다",games:"게임 선택",name:"예약자 이름",arrival:"도착 예정 시간",apply:"예약 신청 (테스트)",recent:"내 예약 확인",empty:"이 브라우저에 신청한 예약이 없습니다.",pending:"승인 대기",confirmed:"예약 확정",waitlisted:"대기 등록",rejected:"예약 불가",checked_in:"입장 완료",cashier:"캐셔 데모",guest:"플레이어 예약",confirm:"확정",wait:"대기",reject:"거절",check:"입장",status:"예약 현황",example:"예시 일정 · 실시간 좌석 정보 연동 예정",admin:"테스트용 캐셔 화면입니다. 인증 연결 전 실제 운영에 사용하지 마세요.",reserved:"신청이 접수되었습니다. (이 브라우저의 테스트 기록에만 저장)",invalid:"예약자 이름을 입력하세요.",none:"처리할 예약이 없습니다.",history:"테스트 신청 목록",clear:"테스트 기록 삭제"},
 en:{tag:"DA NANG · TABLE RESERVATION",heading:"Reserve your poker seat",sub:"Choose a game and your estimated arrival time.",demo:"DEMO ONLY · Requests are not sent to the poker room",games:"Choose a game",name:"Player name",arrival:"Estimated arrival",apply:"Request booking (test)",recent:"My test bookings",empty:"No booking made in this browser.",pending:"Pending",confirmed:"Confirmed",waitlisted:"Waitlisted",rejected:"Unavailable",checked_in:"Checked in",cashier:"Cashier demo",guest:"Book a seat",confirm:"Confirm",wait:"Waitlist",reject:"Reject",check:"Check in",status:"Booking status",example:"Sample schedules · live seat data coming soon",admin:"This cashier screen is for testing only. Do not use for real operations until authentication is connected.",reserved:"Test request saved in this browser only.",invalid:"Enter your name.",none:"No requests yet.",history:"Test bookings",clear:"Clear test records"},
 vi:{tag:"DA NANG · TABLE RESERVATION",heading:"Đặt chỗ chơi poker dễ dàng",sub:"Chọn trò chơi và giờ bạn dự kiến đến.",demo:"CHỈ LÀ BẢN THỬ · Chưa gửi đặt chỗ đến phòng poker",games:"Chọn trò chơi",name:"Tên người chơi",arrival:"Giờ dự kiến đến",apply:"Gửi yêu cầu (thử nghiệm)",recent:"Đặt chỗ của tôi",empty:"Chưa có đặt chỗ trên trình duyệt này.",pending:"Chờ duyệt",confirmed:"Đã xác nhận",waitlisted:"Danh sách chờ",rejected:"Không còn chỗ",checked_in:"Đã đến",cashier:"Thử nghiệm thu ngân",guest:"Đặt chỗ",confirm:"Xác nhận",wait:"Chờ",reject:"Từ chối",check:"Đã đến",status:"Trạng thái đặt chỗ",example:"Lịch ví dụ · sẽ kết nối chỗ trống trực tiếp",admin:"Màn hình thu ngân chỉ để thử nghiệm. Không dùng để vận hành thật trước khi có đăng nhập.",reserved:"Yêu cầu thử nghiệm chỉ lưu trên trình duyệt.",invalid:"Nhập tên người chơi.",none:"Chưa có yêu cầu.",history:"Danh sách thử nghiệm",clear:"Xóa dữ liệu thử"}
} as const;
const KEY="dream-poker-reservation-prototype-v1";
export default function Home(){
 const [lang,setLang]=useState<Lang>("ko");
 const [view,setView]=useState<"player"|"cashier">("player");
 const [game,setGame]=useState(games[1].name);
 const [name,setName]=useState("");
 const [arrival,setArrival]=useState("19:00");
 const [bookings,setBookings]=useState<Booking[]>([]);
 const [ready,setReady]=useState(false);
 const [notice,setNotice]=useState("");
 const t=dictionary[lang];
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const arr=JSON.parse(saved);if(Array.isArray(arr))setBookings(arr)}}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(bookings))},[bookings,ready]);
 const myBookings=useMemo(()=>bookings.filter(b=>b.name.toLowerCase()===name.trim().toLowerCase() && name.trim()),[bookings,name]);
 function request(){if(!name.trim()){setNotice(t.invalid);return}const row:Booking={id:crypto.randomUUID(),name:name.trim().slice(0,80),game,arrival,status:"pending",createdAt:new Date().toISOString()};setBookings(prev=>[row,...prev]);setNotice(t.reserved)}
 function update(id:string,status:Status){setBookings(prev=>prev.map(b=>b.id===id?{...b,status}:b))}
 return <main className="shell"><header className="header"><div className="logo"><span className="symbol">♠</span><div><strong>DREAM POKER</strong><small>{t.tag}</small></div></div><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ko">한국어</option><option value="en">English</option><option value="vi">Tiếng Việt</option></select></header>
 <div className="warning" role="status">{t.demo}</div>
 <div className="switch"><button className={view==="player"?"selected":""} onClick={()=>setView("player")}>{t.guest}</button><button className={view==="cashier"?"selected":""} onClick={()=>setView("cashier")}>{t.cashier}</button></div>
 {view==="player"?<><section className="hero"><div className="eyebrow">DREAM POKER DA NANG</div><h1>{t.heading}</h1><p>{t.sub}</p></section><section className="panel"><div className="sectionTitle"><h2>{t.games}</h2><small>{t.example}</small></div><div className="gameGrid">{games.map(g=><button key={g.name} className={"gameCard "+(game===g.name?"active":"")} onClick={()=>setGame(g.name)}><span className="gameName">{g.name}</span><span className="gameTime">{g.time} · {g.seats} SEATS</span><span className="demoLabel">DEMO</span></button>)}</div><div className="form"><label>{t.name}<input maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="NAME / 이름 / Tên"/></label><label>{t.arrival}<input type="time" value={arrival} onChange={e=>setArrival(e.target.value)}/></label><button className="primary" onClick={request}>{t.apply} →</button>{notice&&<p className="notice">{notice}</p>}</div></section><section className="panel"><h2>{t.recent}</h2>{myBookings.length?myBookings.map(b=><BookingCard key={b.id} booking={b} label={t[b.status]}/>):<p className="muted">{t.empty}</p>}</section></>:<section className="panel"><h1>{t.cashier}</h1><p className="muted">{t.admin}</p><div className="listTop"><h2>{t.history} ({bookings.length})</h2><button className="outline" onClick={()=>{if(window.confirm("Delete all demo bookings?"))setBookings([])}}>{t.clear}</button></div>{bookings.length?bookings.map(b=><div className="cashierRow" key={b.id}><BookingCard booking={b} label={t[b.status]}/><div className="actions"><button onClick={()=>update(b.id,"confirmed")}>{t.confirm}</button><button onClick={()=>update(b.id,"waitlisted")}>{t.wait}</button><button onClick={()=>update(b.id,"rejected")}>{t.reject}</button><button onClick={()=>update(b.id,"checked_in")}>{t.check}</button></div></div>):<p className="muted">{t.none}</p>}</section>}
 <footer>© Dream Poker · Prototype v0.1 · No live reservations</footer></main>
}
function BookingCard({booking,label}:{booking:Booking;label:string}){return <div className="booking"><div><strong>{booking.name}</strong><p>{booking.game} · {booking.arrival}</p></div><span className={"status "+booking.status}>{label}</span></div>}
