"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {db,configured} from "../lib/db";
import DeskTools from "./DeskTools";
type Lang="ko"|"en"|"vi";
type Status="pending"|"confirmed"|"waitlisted"|"rejected"|"cancelled"|"checked_in"|"no_show";
type Game={id:string;title:string;starts_at:string;capacity:number;is_open:boolean;table_no:string;description:string};
type Stats={game_id:string;confirmed_count:number;pending_count:number;waiting_count:number};
type Booking={id:string;game_id:string;player_name:string;arrival_at:string;status:Status;created_at:string;lookup_token?:string};
type Own=Booking&{game_title:string};
type Profile={role:string;display_name:string;active:boolean};
const TOKEN_KEY="dream-reservation-tokens-v1";
const labels={
 ko:{home:"게임 예약",cashier:"캐셔 관리",admin:"게임 관리",subtitle:"게임을 선택하고 예약 신청을 해주세요.",demo:"실시간 연결 준비 중입니다. 현재 예약을 접수하지 않습니다.",available:"예약 가능",full:"만석 · 대기 접수",closed:"예약 마감",seats:"확정",pending:"승인 대기",waitlisted:"대기 등록",confirmed:"예약 확정",checked_in:"입장 완료",rejected:"예약 거절",cancelled:"취소됨",no_show:"노쇼",name:"예약자 이름",arrival:"도착 예정 시간",book:"예약 신청",mine:"내 예약",empty:"예약 이력이 없습니다.",request:"예약 신청 접수. 캐셔 승인을 기다려주세요.",approve:"예약 확정",wait:"대기 등록",reject:"예약 거절",cancel:"예약 취소",checkin:"입장 완료",noshow:"노쇼",login:"직원 로그인",id:"아이디 또는 이메일",password:"비밀번호",signIn:"로그인",signOut:"로그아웃",access:"직원 권한이 없는 계정입니다.",staff:"실시간 예약 처리",reload:"새로고침",all:"전체",create:"게임 등록",title:"게임명",starts:"시작 일시",capacity:"좌석 정원",table:"테이블 번호",description:"안내 문구",save:"게임 추가",enable:"예약 열기",disable:"예약 닫기",help:"예약 접수 후 캐셔가 확인해야 확정됩니다. 신청만으로 좌석이 보장되지 않습니다.",confirmCancel:"예약을 취소할까요?",audit:"변경 기록",logempty:"아직 기록이 없습니다.",noGames:"등록된 게임이 없습니다.",capacityHint:"좌석 수는 캐셔가 확정한 예약 기준입니다.",test:"실제 게임이 등록되면 이곳에 표시됩니다.",select:"예약할 게임",reserved:"신청",sound:"새 예약 알림음",filter:"게임 필터"},
 en:{home:"Book a seat",cashier:"Cashier",admin:"Game management",subtitle:"Choose your game and request a seat.",demo:"Live connection is not configured. Reservations are disabled.",available:"Available",full:"Full · waitlist",closed:"Closed",seats:"confirmed",pending:"Pending",waitlisted:"Waitlisted",confirmed:"Confirmed",checked_in:"Checked in",rejected:"Rejected",cancelled:"Cancelled",no_show:"No show",name:"Player name",arrival:"Estimated arrival",book:"Request reservation",mine:"My bookings",empty:"No saved bookings.",request:"Request received. Please wait for cashier approval.",approve:"Confirm",wait:"Waitlist",reject:"Reject",cancel:"Cancel",checkin:"Checked in",noshow:"No show",login:"Staff sign in",id:"Username or email",password:"Password",signIn:"Sign in",signOut:"Sign out",access:"This account does not have staff access.",staff:"Manage live requests",reload:"Refresh",all:"All",create:"Add game",title:"Game name",starts:"Game starts",capacity:"Seat capacity",table:"Table number",description:"Description",save:"Create game",enable:"Open",disable:"Close",help:"Your seat is only confirmed when the cashier approves your request.",confirmCancel:"Cancel this reservation?",audit:"Audit history",logempty:"No changes yet.",noGames:"No games scheduled.",capacityHint:"Seats represent cashier-confirmed bookings.",test:"Games will appear here once scheduled.",select:"Select game",reserved:"requests",sound:"New request sound",filter:"Filter by game"},
 vi:{home:"Đặt chỗ",cashier:"Thu ngân",admin:"Quản lý trò chơi",subtitle:"Chọn trò chơi và gửi yêu cầu đặt chỗ.",demo:"Chưa kết nối dữ liệu trực tiếp. Tạm ngừng nhận đặt chỗ.",available:"Còn chỗ",full:"Hết chỗ · chờ",closed:"Đóng",seats:"đã xác nhận",pending:"Chờ duyệt",waitlisted:"Danh sách chờ",confirmed:"Đã xác nhận",checked_in:"Đã đến",rejected:"Bị từ chối",cancelled:"Đã hủy",no_show:"Không đến",name:"Tên người chơi",arrival:"Giờ dự kiến đến",book:"Gửi yêu cầu",mine:"Đặt chỗ của tôi",empty:"Chưa có đặt chỗ.",request:"Đã gửi yêu cầu. Chờ thu ngân duyệt.",approve:"Xác nhận",wait:"Chờ",reject:"Từ chối",cancel:"Hủy",checkin:"Đã đến",noshow:"Không đến",login:"Đăng nhập nhân viên",id:"Tên đăng nhập hoặc email",password:"Mật khẩu",signIn:"Đăng nhập",signOut:"Đăng xuất",access:"Tài khoản không có quyền nhân viên.",staff:"Xử lý đặt chỗ",reload:"Làm mới",all:"Tất cả",create:"Tạo trò chơi",title:"Tên trò chơi",starts:"Giờ bắt đầu",capacity:"Số ghế",table:"Số bàn",description:"Ghi chú",save:"Tạo trò chơi",enable:"Mở",disable:"Đóng",help:"Đặt chỗ chỉ được xác nhận sau khi thu ngân duyệt.",confirmCancel:"Hủy đặt chỗ này?",audit:"Lịch sử thay đổi",logempty:"Chưa có lịch sử.",noGames:"Chưa có trò chơi.",capacityHint:"Ghế đã được nhân viên xác nhận.",test:"Trò chơi sẽ xuất hiện khi được tạo.",select:"Chọn trò chơi",reserved:"yêu cầu",sound:"Âm báo đặt chỗ mới",filter:"Lọc trò chơi"}
} as const;
const fmt=(x:string,lang:Lang)=>new Date(x).toLocaleString(lang==="ko"?"ko-KR":lang==="vi"?"vi-VN":"en-GB",{timeZone:"Asia/Ho_Chi_Minh",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
const localDatetime=(d:Date)=>{const v=new Date(d.getTime()+7*3600000);return v.toISOString().slice(0,16)};
export default function Home(){
 const [lang,setLang]=useState<Lang>("ko"),[view,setView]=useState<"guest"|"cashier">("guest");
 const [games,setGames]=useState<Game[]>([]),[stats,setStats]=useState<Stats[]>([]),[selected,setSelected]=useState("");
 const [name,setName]=useState(""),[arrival,setArrival]=useState(localDatetime(new Date(Date.now()+3600000)));
 const [mine,setMine]=useState<Own[]>([]),[tokens,setTokens]=useState<string[]>([]);
 const [bookings,setBookings]=useState<Booking[]>([]),[profile,setProfile]=useState<Profile|null>(null);
 const [email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [filter,setFilter]=useState("all"),[sound,setSound]=useState(false);
 const [newGame,setNewGame]=useState({title:"5M TIME ATTACK",starts:localDatetime(new Date(Date.now()+3600000)),capacity:"9",table_no:"",description:""});
 const [audit,setAudit]=useState<Array<{id:number;reservation_id:string;previous_status:string|null;new_status:string;created_at:string;actor:string|null}>>([]);
 const [sessionUser,setSessionUser]=useState("");
 const lastSeen=useRef<string[]>([]),audioCtx=useRef<AudioContext|null>(null);
 const t=labels[lang];
 const staff=profile?.active && (profile.role==="admin"||profile.role==="staff");
 const selectedGame=games.find(g=>g.id===selected);
 const selectedStat=stats.find(s=>s.game_id===selected);
 const activeGames=games.filter(g=>g.is_open&&new Date(g.starts_at).getTime()>Date.now()-12*3600000);
 const notice=(value:string)=>{setMessage(value);};
 const loadPublic=useCallback(async()=>{if(!db)return;const [g,st]=await Promise.all([db.from("reservation_games").select("*").order("starts_at",{ascending:true}).gte("starts_at",new Date(Date.now()-12*3600000).toISOString()),db.rpc("reservation_public_stats")]);if(g.error)notice(g.error.message);else setGames(g.data||[]);if(st.error)notice(st.error.message);else setStats((st.data||[]).map((r:any)=>({...r,confirmed_count:Number(r.confirmed_count),pending_count:Number(r.pending_count),waiting_count:Number(r.waiting_count)})));setLoading(false)},[]);
 const loadMine=useCallback(async(ts:string[])=>{if(!db||!ts.length){setMine([]);return}const results=await Promise.all(ts.slice(0,30).map(async token=>{const {data}=await db.rpc("lookup_poker_reservation",{p_token:token});return data?.[0]?{...data[0],lookup_token:token}:null}));setMine(results.filter(Boolean) as Own[])},[]);
 const loadStaff=useCallback(async()=>{if(!db)return;const {data,error}=await db.from("reservations").select("id,game_id,player_name,arrival_at,status,created_at").order("created_at",{ascending:false}).limit(500);if(!error)setBookings(data||[]);const a=await db.from("reservation_audit").select("*").order("created_at",{ascending:false}).limit(100);if(!a.error)setAudit(a.data||[])},[]);
 useEffect(()=>{try{const list=JSON.parse(localStorage.getItem(TOKEN_KEY)||"[]");if(Array.isArray(list))setTokens(list.filter((x:any)=>typeof x==="string"))}catch{}},[]);
 useEffect(()=>{if(configured)void loadPublic();else setLoading(false);},[loadPublic]);
 useEffect(()=>{if(db)void loadMine(tokens)},[tokens,loadMine]);
 useEffect(()=>{if(!db)return;const client=db;let live=true;const check=async()=>{const s=await client.auth.getUser();if(!live)return;const u=s.data.user;if(!u){setProfile(null);setSessionUser("");return}setSessionUser(u.id);const p=await client.from("user_profiles").select("role,display_name,active").eq("user_id",u.id).maybeSingle();if(live)setProfile(p.data as Profile|null)};void check();const {data:{subscription}}=client.auth.onAuthStateChange(()=>{void check()});return()=>{live=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!staff)return;void loadStaff()},[staff,loadStaff]);
 useEffect(()=>{if(!configured)return;const timer=setInterval(()=>{void loadPublic();void loadMine(tokens);if(staff)void loadStaff()},9000);const focus=()=>{void loadPublic();void loadMine(tokens);if(staff)void loadStaff()};window.addEventListener("focus",focus);return()=>{clearInterval(timer);window.removeEventListener("focus",focus)}},[staff,tokens,loadPublic,loadMine,loadStaff]);
 useEffect(()=>{const ids=bookings.filter(b=>b.status==="pending").map(b=>b.id);if(sound&&lastSeen.current.length&&ids.some(id=>!lastSeen.current.includes(id))){try{const ctx=audioCtx.current||new AudioContext();audioCtx.current=ctx;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=740;gain.gain.value=.07;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.24)}catch{}}lastSeen.current=ids},[bookings,sound]);
 async function requestBooking(){if(!db||!selectedGame)return;if(name.trim().length<2){notice("이름을 2글자 이상 입력해주세요.");return}setBusy(true);const {data,error}=await db.rpc("request_poker_reservation",{p_game:selectedGame.id,p_name:name.trim(),p_arrival:new Date(arrival+"+07:00").toISOString()});setBusy(false);if(error){notice(error.message);return}const token=data?.[0]?.reservation_token;if(token){const next=[String(token),...tokens].slice(0,30);setTokens(next);localStorage.setItem(TOKEN_KEY,JSON.stringify(next));notice(t.request);void loadMine(next);void loadPublic()}}
 async function cancelBooking(token:string){if(!db||!confirm(t.confirmCancel))return;setBusy(true);const {data,error}=await db.rpc("cancel_poker_reservation",{p_token:token});setBusy(false);notice(error?.message||(!data?"Cannot cancel this booking":"Cancelled"));void loadMine(tokens);void loadPublic()}
 async function login(){if(!db)return;setBusy(true);let authEmail=email.trim().toLowerCase();if(!authEmail.includes("@")){const r=await db.rpc("resolve_login_email",{p_username:authEmail});if(r.error||typeof r.data!=="string"||!r.data){notice(r.error?.message||"계정을 찾을 수 없습니다.");setBusy(false);return}authEmail=r.data}const {error}=await db.auth.signInWithPassword({email:authEmail,password});setBusy(false);notice(error?.message||"");}
 async function logout(){await db?.auth.signOut();setProfile(null);setSessionUser("");setView("guest")}
 async function manage(id:string,status:Status){if(!db)return;setBusy(true);const {error}=await db.rpc("manage_poker_reservation",{p_id:id,p_status:status});setBusy(false);if(error)notice(error.message);else{notice("Saved");void loadStaff();void loadPublic();}}
 async function createGame(){if(!db)return;setBusy(true);const {error}=await db.from("reservation_games").insert({title:newGame.title.trim(),starts_at:new Date(newGame.starts+"+07:00").toISOString(),capacity:Number(newGame.capacity),table_no:newGame.table_no,description:newGame.description,is_open:true});setBusy(false);notice(error?.message||"Game created");if(!error)void loadPublic()}
 async function setOpen(game:Game,is_open:boolean){if(!db)return;setBusy(true);const {error}=await db.from("reservation_games").update({is_open}).eq("id",game.id);setBusy(false);notice(error?.message||"Saved");void loadPublic()}
 const bookByGame=useMemo(()=>bookings.filter(b=>filter==="all"||b.game_id===filter),[bookings,filter]);
 return <main className="shell"><header className="header"><div className="brand"><span className="mark">♠</span><div><strong>DREAM POKER</strong><small>DA NANG · RESERVATIONS</small></div></div><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ko">한국어</option><option value="en">English</option><option value="vi">Tiếng Việt</option></select></header>
 {!configured&&<div className="warning">{t.demo} · NEXT_PUBLIC_SUPABASE_ANON_KEY</div>}
 <nav className="tabs"><button className={view==="guest"?"chosen":""} onClick={()=>setView("guest")}>{t.home}</button><button className={view==="cashier"?"chosen":""} onClick={()=>setView("cashier")}>{t.cashier}</button></nav>
 {message&&<div className="alert" role="status" onClick={()=>setMessage("")}>{message} <span>×</span></div>}
 {view==="guest"?<><section className="hero"><div className="eyebrow">LIVE RESERVATIONS</div><h1>{t.home}</h1><p>{t.subtitle}</p></section><section className="panel"><div className="sectionHead"><h2>{t.select}</h2><span className="hint">{t.capacityHint}</span></div><div className="gameList">{loading?<p>Loading…</p>:!activeGames.length?<p className="muted">{t.noGames}</p>:activeGames.map(g=>{const st=stats.find(x=>x.game_id===g.id);const free=Math.max(0,g.capacity-(st?.confirmed_count||0));return <button key={g.id} className={"gameCard "+(selected===g.id?"active":"")} onClick={()=>{setSelected(g.id);setArrival(localDatetime(new Date(Math.max(Date.now()+1800000,new Date(g.starts_at).getTime()))))}}><div><strong>{g.title}</strong><small>{fmt(g.starts_at,lang)} {g.table_no?"· TABLE "+g.table_no:""}</small><small>{g.description}</small></div><div className="gameNumbers"><b className={free?"green":"gold"}>{free}/{g.capacity}</b><small>{free?t.available:t.full}</small><small>{st?.pending_count||0} {t.pending}</small></div></button>})}</div></section>
 <section className="panel"><h2>{t.book}</h2><p className="muted">{t.help}</p><div className="bookingForm"><label>{t.name}<input autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="NAME / 이름 / Tên"/></label><label>{t.arrival}<input type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></label><button className="primary" disabled={!configured||!selected||busy} onClick={()=>void requestBooking()}>{busy?"…":t.book} →</button></div></section>
 <section className="panel"><h2>{t.mine}</h2>{mine.length?mine.map((b,i)=><div className="bookingRow" key={b.id}><div><strong>{b.game_title}</strong><small>{fmt(b.arrival_at,lang)} · {b.player_name}</small><small>#{b.id.slice(0,8)}</small></div><div className="bookingRight"><span className={"status "+b.status}>{t[b.status]}</span>{["pending","confirmed","waitlisted"].includes(b.status)&&<button className="quiet" disabled={busy} onClick={()=>void cancelBooking(b.lookup_token||"")}>{t.cancel}</button>}</div></div>):<p className="muted">{t.empty}</p>}</section></>:
 !sessionUser?<section className="panel login"><h1>{t.login}</h1><label>{t.id}<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>{t.password}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={busy||!configured} onClick={()=>void login()}>{t.signIn}</button></section>:
 !staff?<section className="panel"><p>{t.access}</p><button onClick={()=>void logout()}>{t.signOut}</button></section>:
 <><DeskTools games={games} bookings={bookings} language={lang} refresh={()=>{void loadStaff();void loadPublic()}}/><section className="panel"><div className="sectionHead"><div><h1>{t.staff}</h1><p className="muted">{profile?.display_name||profile?.role}</p></div><button className="outline" onClick={()=>void logout()}>{t.signOut}</button></div><div className="toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label={t.filter}><option value="all">{t.all}</option>{games.map(g=><option key={g.id} value={g.id}>{g.title} · {fmt(g.starts_at,lang)}</option>)}</select><label className="sound"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/>{t.sound}</label><button className="outline" onClick={()=>{void loadStaff();void loadPublic()}}>{t.reload}</button></div>{bookByGame.length===0?<p className="muted">{t.empty}</p>:bookByGame.map(b=><div className="operatorBooking" key={b.id}><div className="operatorHeader"><div><strong>{b.player_name}</strong><small>{games.find(g=>g.id===b.game_id)?.title||"Game"} · {fmt(b.arrival_at,lang)}</small><small>Requested {fmt(b.created_at,lang)}</small></div><span className={"status "+b.status}>{t[b.status]}</span></div><div className="actions">{(["confirmed","waitlisted","rejected","checked_in","no_show","cancelled"] as Status[]).map(k=><button key={k} disabled={busy||b.status===k} className={k==="confirmed"?"emphasis":""} onClick={()=>void manage(b.id,k)}>{({confirmed:t.approve,waitlisted:t.wait,rejected:t.reject,checked_in:t.checkin,no_show:t.noshow,cancelled:t.cancel} as Record<string,string>)[k]}</button>)}</div></div>)}</section>
 {profile?.role==="admin"&&<section className="panel"><h2>{t.admin}</h2><div className="newGame"><label>{t.title}<input value={newGame.title} onChange={e=>setNewGame({...newGame,title:e.target.value})}/></label><label>{t.starts}<input type="datetime-local" value={newGame.starts} onChange={e=>setNewGame({...newGame,starts:e.target.value})}/></label><label>{t.capacity}<input type="number" min="1" max="30" value={newGame.capacity} onChange={e=>setNewGame({...newGame,capacity:e.target.value})}/></label><label>{t.table}<input value={newGame.table_no} onChange={e=>setNewGame({...newGame,table_no:e.target.value})}/></label><label>{t.description}<input value={newGame.description} onChange={e=>setNewGame({...newGame,description:e.target.value})}/></label><button className="primary" disabled={busy||!newGame.title.trim()||Number(newGame.capacity)<1||Number(newGame.capacity)>30} onClick={()=>void createGame()}>{t.save}</button></div>{games.map(g=><div className="gameControl" key={g.id}><span>{g.title} · {fmt(g.starts_at,lang)}</span><button disabled={busy} onClick={()=>void setOpen(g,!g.is_open)}>{g.is_open?t.disable:t.enable}</button></div>)}</section>}
 <section className="panel"><h2>{t.audit}</h2>{!audit.length?<p className="muted">{t.logempty}</p>:audit.slice(0,50).map(a=><div className="auditRow" key={a.id}><span>{a.reservation_id.slice(0,8)} · {a.previous_status||"new"} → {a.new_status}</span><small>{fmt(a.created_at,lang)}</small></div>)}</section></>}
 <footer>© DREAM POKER DA NANG · Reservations</footer></main>
}
