"use client";
import {useEffect,useRef,useState} from "react";
type Booking={id:string;game_id:string;player_name:string;status:string;created_at:string};
type Game={id:string;table_no:string;game_no?:string;title:string};
type Setting={enabled:boolean;mode:"voice"|"bell"|"double"|"soft"|"casino"|"arcade"|"royal"|"retro";voice:string;volume:number;rate:number};
const KEY="dream-reservation-audio-v2";
const defaults:Setting={enabled:false,mode:"voice",voice:"",volume:0.75,rate:1};
export default function ReservationAlerts({bookings,games,loaded,lang="ko"}:{bookings:Booking[];games:Game[];loaded:boolean;lang?:"ko"|"en"|"vi"}){
 const tr=(ko:string,en:string,vi:string)=>lang==="en"?en:lang==="vi"?vi:ko;
 const locale=lang==="en"?"en":lang==="vi"?"vi":"ko";
 const [setting,setSetting]=useState<Setting>(defaults);
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 const [open,setOpen]=useState(false),[toast,setToast]=useState("");
 const popoverRef=useRef<HTMLDivElement|null>(null),controlRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!open)return;const closeOutside=(event:PointerEvent)=>{const target=event.target as Node;if(!popoverRef.current?.contains(target)&&!controlRef.current?.contains(target))setOpen(false)};const closeEscape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("pointerdown",closeOutside);document.addEventListener("keydown",closeEscape);return()=>{document.removeEventListener("pointerdown",closeOutside);document.removeEventListener("keydown",closeEscape)}},[open]);
 const ready=useRef(false),seen=useRef<Set<string>>(new Set()),ctx=useRef<AudioContext|null>(null),settingsRef=useRef(setting),gamesRef=useRef(games);
 useEffect(()=>{settingsRef.current=setting;gamesRef.current=games;try{localStorage.setItem(KEY,JSON.stringify(setting))}catch{}},[setting,games]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved&&typeof saved==="object")setSetting({...defaults,...saved,enabled:false})}catch{}const load=()=>setVoices(window.speechSynthesis?.getVoices()||[]);load();window.speechSynthesis?.addEventListener?.("voiceschanged",load);return()=>window.speechSynthesis?.removeEventListener?.("voiceschanged",load)},[]);
 function alertFor(b:Booking){const g=gamesRef.current.find(x=>x.id===b.game_id);const target=g?.table_no?`${g.table_no}번 테이블`:"다음";const no=g?.game_no?` ${g.game_no}번 게임`:" 게임";return lang==="en"?`${b.player_name} reserved ${g?.table_no?"Table "+g.table_no:"the next table"}${g?.game_no?", Game No."+g.game_no:""}.`:lang==="vi"?`${b.player_name} đã đặt chỗ ${g?.table_no?"Bàn "+g.table_no:"bàn tiếp theo"}${g?.game_no?", game số "+g.game_no:""}.`:`${b.player_name}님께서 ${target}의${no}을 예약하셨습니다.`;}
 function bell(mode:Setting["mode"],volume:number){try{const audio=ctx.current||new AudioContext();ctx.current=audio;void audio.resume();const t=audio.currentTime;const frequencies=mode==="double"?[660,880,660]:mode==="soft"?[523,659,784]:mode==="casino"?[784,988,1175,1568]:mode==="arcade"?[880,660,988,1318]:mode==="royal"?[392,523,659,784]:mode==="retro"?[440,880,440,880]:[880,1046];frequencies.forEach((freq,i)=>{const oscillator=audio.createOscillator(),gain=audio.createGain();const at=t+i*0.17;oscillator.type=mode==="soft"||mode==="royal"?"sine":mode==="arcade"||mode==="retro"?"square":"triangle";oscillator.frequency.value=freq;gain.gain.setValueAtTime(0.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(0.001,volume*0.15),at+0.025);gain.gain.exponentialRampToValueAtTime(0.0001,at+0.14);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(at);oscillator.stop(at+0.16)})}catch{}}
 function play(text:string,current:Setting){if(current.mode!=="voice"){bell(current.mode,current.volume);return;}if(!("speechSynthesis" in window)){bell("double",current.volume);return;}const utterance=new SpeechSynthesisUtterance(text);const options=window.speechSynthesis.getVoices();utterance.voice=options.find(v=>v.voiceURI===current.voice)||options.find(v=>v.lang.toLowerCase().startsWith(locale))||null;utterance.lang=utterance.voice?.lang||(lang==="ko"?"ko-KR":lang==="vi"?"vi-VN":"en-US");utterance.rate=current.rate;utterance.volume=current.volume;window.speechSynthesis.cancel();window.speechSynthesis.speak(utterance);}
 useEffect(()=>{if(!loaded)return;const current=bookings.filter(b=>b.status==="pending");if(!ready.current){seen.current=new Set(bookings.map(b=>b.id));ready.current=true;return;}const fresh=current.filter(b=>!seen.current.has(b.id));bookings.forEach(b=>seen.current.add(b.id));if(!fresh.length)return;const item=fresh[0];const text=alertFor(item);setToast(fresh.length>1?`${text} · +${fresh.length-1}`:text);if(settingsRef.current.enabled){if(fresh.length>1)play(tr(`새 예약 ${fresh.length}건이 접수되었습니다. ${text}`,`${fresh.length} new reservations. ${text}`,`Có ${fresh.length} đặt chỗ mới. ${text}`),settingsRef.current);else play(text,settingsRef.current)}},[bookings,loaded]);
 function enable(){const updated={...setting,enabled:!setting.enabled};setSetting(updated);if(!setting.enabled){bell("soft",updated.volume);setOpen(true)}else window.speechSynthesis?.cancel();}
 const preferred=voices.filter(v=>v.lang.toLowerCase().startsWith(locale));const voiceOptions=preferred.length?preferred:voices;
 return <><div className="notifyControl" ref={controlRef}><button type="button" role="switch" aria-checked={setting.enabled} aria-label={tr("음성 알림","Sound alerts","Thông báo âm thanh")} className={"notifySwitch "+(setting.enabled?"notifyEnabled":"")} onClick={enable}><span className="switchTrack"><span className="switchThumb"/></span><span>{setting.enabled?tr("알림 ON","Alerts ON","Bật âm"):tr("알림 OFF","Alerts OFF","Tắt âm")}</span></button><button onClick={()=>setOpen(v=>!v)} title={tr("알림음 및 목소리 설정","Sound & voice settings","Cài đặt âm báo và giọng nói")}>{tr("⚙ 설정","⚙ Settings","⚙ Cài đặt")}</button></div>
 {toast&&<div className="bookingToast" role="status"><strong>{tr("♠ 신규 예약 접수","♠ New reservation","♠ Đặt chỗ mới")}</strong><p>{toast}</p><button onClick={()=>setToast("")}>{tr("닫기","Close","Đóng")}</button></div>}
 {open&&<div className="notificationSettings" ref={popoverRef} role="dialog" aria-label={tr("예약 알림 설정","Reservation alerts","Cài đặt thông báo")}><div className="notificationTitle"><strong>{tr("예약 알림 설정","Reservation alerts","Cài đặt thông báo")}</strong><button onClick={()=>setOpen(false)}>{tr("닫기 ×","Close ×","Đóng ×")}</button></div><label>{tr("알림 방식","Alert type","Kiểu thông báo")}<select value={setting.mode} onChange={e=>setSetting({...setting,mode:e.target.value as Setting["mode"]})}><option value="voice">{tr("한국어 음성 안내","Voice announcement","Thông báo bằng giọng nói")}</option><option value="bell">{tr("밝은 호출음","Bright chime","Chuông sáng")}</option><option value="double">{tr("긴급 3회 벨","Triple bell","Chuông 3 lần")}</option><option value="soft">{tr("부드러운 차임","Gentle chime","Chuông nhẹ")}</option><option value="casino">🎰 Casino Jackpot</option><option value="arcade">👾 Arcade</option><option value="royal">♛ Royal Bell</option><option value="retro">🕹 Retro Game</option></select></label>{setting.mode==="voice"&&<><label>{tr("목소리","Voice","Giọng đọc")}<select value={setting.voice} onChange={e=>setSetting({...setting,voice:e.target.value})}><option value="">{tr("기본 기기 목소리","Default system voice","Giọng mặc định")}</option>{voiceOptions.map(v=><option value={v.voiceURI} key={v.voiceURI}>{v.name} ({v.lang})</option>)}</select></label><label>{tr("말하기 속도 ","Speech speed ","Tốc độ đọc ")}<span>{setting.rate.toFixed(1)}배</span><input type="range" min="0.7" max="1.3" step="0.1" value={setting.rate} onChange={e=>setSetting({...setting,rate:Number(e.target.value)})}/></label></>}<label>{tr("음량 ","Volume ","Âm lượng ")}<span>{Math.round(setting.volume*100)}%</span><input type="range" min="0.1" max="1" step="0.1" value={setting.volume} onChange={e=>setSetting({...setting,volume:Number(e.target.value)})}/></label><button className="notificationPreview" onClick={()=>play(tr("김지원님께서 5번 테이블의 다음 게임을 예약하셨습니다.","A guest reserved the next game at Table 5.","Có khách đặt chỗ trò tiếp theo tại Bàn 5."),setting)}>{tr("▶ 알림 미리 듣기","▶ Preview sound","▶ Nghe thử")}</button><small>{tr("PC에서 직원 화면을 열어둔 동안 동작합니다. 사용자가 알림을 켜야 소리가 재생되며, 목소리는 기기에 설치된 음성을 사용합니다.","Works while the staff page remains open. Click Enable alerts to allow playback. Voices depend on your device.","Hoạt động khi trang nhân viên đang mở. Nhấn bật thông báo để nghe. Giọng nói tùy thuộc thiết bị.")}</small></div>}</>;
}
