"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {db,configured} from "../lib/db";
import DeskTools from "./DeskTools";
import MemberBooking from "./MemberBooking";
import TelegramSetup from "./TelegramSetup";
import StaffDashboard from "./StaffDashboard";
import BrandSettings,{DEFAULT_BRAND,type Brand} from "./BrandSettings";
type Lang="ko"|"en"|"vi";
type Status="pending"|"confirmed"|"waitlisted"|"rejected"|"cancelled"|"checked_in"|"no_show";
type Game={id:string;title:string;starts_at:string;capacity:number;is_open:boolean;table_no:string;game_no?:string;description:string};
type Stats={game_id:string;confirmed_count:number;pending_count:number;waiting_count:number};
type Booking={id:string;game_id:string;player_name:string;arrival_at:string;status:Status;created_at:string;member_number?:string|null;guest_note?:string|null;lookup_token?:string};
type Own=Booking&{game_title:string};
type Profile={role:string;display_name:string;active:boolean};
const TOKEN_KEY="dream-reservation-tokens-v1";
const labels={
 ko:{home:"게임 예약",cashier:"캐셔 관리",admin:"게임 관리",subtitle:"게임을 선택하고 예약 신청을 해주세요.",demo:"실시간 연결 준비 중입니다. 현재 예약을 접수하지 않습니다.",available:"예약 가능",full:"만석 · 대기 접수",closed:"예약 마감",seats:"확정",pending:"승인 대기",waitlisted:"대기 등록",confirmed:"예약 확정",checked_in:"입장 완료",rejected:"예약 거절",cancelled:"취소됨",no_show:"노쇼",name:"예약자 이름",arrival:"도착 예정 시간",book:"예약 신청",mine:"내 예약",empty:"예약 이력이 없습니다.",request:"예약 신청 접수. 캐셔 승인을 기다려주세요.",approve:"예약 확정",wait:"대기 등록",reject:"예약 거절",cancel:"예약 취소",checkin:"입장 완료",noshow:"노쇼",login:"직원 로그인",id:"아이디 또는 이메일",password:"비밀번호",signIn:"로그인",signOut:"로그아웃",access:"직원 권한이 없는 계정입니다.",staff:"실시간 예약 처리",reload:"새로고침",all:"전체",create:"게임 등록",title:"게임명",starts:"시작 일시",capacity:"좌석 정원",table:"테이블 번호",description:"안내 문구",save:"게임 추가",enable:"예약 열기",disable:"예약 닫기",help:"예약 접수 후 캐셔가 확인해야 확정됩니다. 신청만으로 좌석이 보장되지 않습니다.",confirmCancel:"예약을 취소할까요?",audit:"변경 기록",logempty:"아직 기록이 없습니다.",noGames:"등록된 게임이 없습니다.",capacityHint:"좌석 수는 캐셔가 확정한 예약 기준입니다.",test:"실제 게임이 등록되면 이곳에 표시됩니다.",select:"예약할 게임",reserved:"신청",sound:"새 예약 알림음",filter:"게임 필터"},
 en:{home:"Book a seat",cashier:"Cashier",admin:"Game management",subtitle:"Choose your game and request a seat.",demo:"Live connection is not configured. Reservations are disabled.",available:"Available",full:"Full · waitlist",closed:"Closed",seats:"confirmed",pending:"Pending",waitlisted:"Waitlisted",confirmed:"Confirmed",checked_in:"Checked in",rejected:"Rejected",cancelled:"Cancelled",no_show:"No show",name:"Player name",arrival:"Estimated arrival",book:"Request reservation",mine:"My bookings",empty:"No saved bookings.",request:"Request received. Please wait for cashier approval.",approve:"Confirm",wait:"Waitlist",reject:"Reject",cancel:"Cancel",checkin:"Checked in",noshow:"No show",login:"Staff sign in",id:"Username or email",password:"Password",signIn:"Sign in",signOut:"Sign out",access:"This account does not have staff access.",staff:"Manage live requests",reload:"Refresh",all:"All",create:"Add game",title:"Game name",starts:"Game starts",capacity:"Seat capacity",table:"Table number",description:"Description",save:"Create game",enable:"Open",disable:"Close",help:"Your seat is only confirmed when the cashier approves your request.",confirmCancel:"Cancel this reservation?",audit:"Audit history",logempty:"No changes yet.",noGames:"No games scheduled.",capacityHint:"Seats represent cashier-confirmed bookings.",test:"Games will appear here once scheduled.",select:"Select game",reserved:"requests",sound:"New request sound",filter:"Filter by game"},
 vi:{home:"Đặt chỗ",cashier:"Thu ngân",admin:"Quản lý trò chơi",subtitle:"Chọn trò chơi và gửi yêu cầu đặt chỗ.",demo:"Chưa kết nối dữ liệu trực tiếp. Tạm ngừng nhận đặt chỗ.",available:"Còn chỗ",full:"Hết chỗ · chờ",closed:"Đóng",seats:"đã xác nhận",pending:"Chờ duyệt",waitlisted:"Danh sách chờ",confirmed:"Đã xác nhận",checked_in:"Đã đến",rejected:"Bị từ chối",cancelled:"Đã hủy",no_show:"Không đến",name:"Tên người chơi",arrival:"Giờ dự kiến đến",book:"Gửi yêu cầu",mine:"Đặt chỗ của tôi",empty:"Chưa có đặt chỗ.",request:"Đã gửi yêu cầu. Chờ thu ngân duyệt.",approve:"Xác nhận",wait:"Chờ",reject:"Từ chối",cancel:"Hủy",checkin:"Đã đến",noshow:"Không đến",login:"Đăng nhập nhân viên",id:"Tên đăng nhập hoặc email",password:"Mật khẩu",signIn:"Đăng nhập",signOut:"Đăng xuất",access:"Tài khoản không có quyền nhân viên.",staff:"Xử lý đặt chỗ",reload:"Làm mới",all:"Tất cả",create:"Tạo trò chơi",title:"Tên trò chơi",starts:"Giờ bắt đầu",capacity:"Số ghế",table:"Số bàn",description:"Ghi chú",save:"Tạo trò chơi",enable:"Mở",disable:"Đóng",help:"Đặt chỗ chỉ được xác nhận sau khi thu ngân duyệt.",confirmCancel:"Hủy đặt chỗ này?",audit:"Lịch sử thay đổi",logempty:"Chưa có lịch sử.",noGames:"Chưa có trò chơi.",capacityHint:"Ghế đã được nhân viên xác nhận.",test:"Trò chơi sẽ xuất hiện khi được tạo.",select:"Chọn trò chơi",reserved:"yêu cầu",sound:"Âm báo đặt chỗ mới",filter:"Lọc trò chơi"}
} as const;
const fmt=(x:string,lang:Lang)=>new Date(x).toLocaleString(lang==="ko"?"ko-KR":lang==="vi"?"vi-VN":"en-GB",{timeZone:"Asia/Ho_Chi_Minh",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"});
const localDatetime=(d:Date)=>{const v=new Date(d.getTime()+7*3600000);return v.toISOString().slice(0,16)};
export default function Home({staffOnly=false}:{staffOnly?:boolean}){
 const [lang,setLang]=useState<Lang>("ko"),[view,setView]=useState<"guest"|"cashier">(staffOnly?"cashier":"guest");
 const [games,setGames]=useState<Game[]>([]),[stats,setStats]=useState<Stats[]>([]),[selected,setSelected]=useState("");
 const [running5m,setRunning5m]=useState<number|null>(null);
 const [brand,setBrand]=useState<Brand>(DEFAULT_BRAND),[theme,setTheme]=useState<"light"|"dark">("dark");
 const [memberMode,setMemberMode]=useState(false),[guestNote,setGuestNote]=useState("");
 const [name,setName]=useState(""),[arrival,setArrival]=useState(localDatetime(new Date(Date.now()+3600000)));
 const [mine,setMine]=useState<Own[]>([]),[tokens,setTokens]=useState<string[]>([]);
 const [bookings,setBookings]=useState<Booking[]>([]),[bookingsLoaded,setBookingsLoaded]=useState(false),[profile,setProfile]=useState<Profile|null>(null);
 const [email,setEmail]=useState(""),[password,setPassword]=useState("");
 const [message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [filter,setFilter]=useState("all"),[sound,setSound]=useState(false);
 const nextEstimate=()=>localDatetime(new Date(Date.now()+60*60000));
 const [newGame,setNewGame]=useState({title:"5M TIME ATTACK",starts:nextEstimate(),capacity:"9",table_no:"4",game_no:"2",description:"시작 예상 시간 · 현장 상황에 따라 변동 가능"});
 const [audit,setAudit]=useState<Array<{id:number;reservation_id:string;previous_status:string|null;new_status:string;created_at:string;actor:string|null}>>([]);
 const [sessionUser,setSessionUser]=useState("");
 const lastSeen=useRef<string[]>([]),audioCtx=useRef<AudioContext|null>(null);
 const t=labels[lang];
 const staff=profile?.active && (profile.role==="admin"||profile.role==="staff");
 const selectedGame=games.find(g=>g.id===selected);
 const selectedStat=stats.find(s=>s.game_id===selected);
 const activeGames=games.filter(g=>g.is_open&&new Date(g.starts_at).getTime()>Date.now()-36*3600000);
 const notice=(value:string)=>{setMessage(value);};
 useEffect(()=>{try{const saved=localStorage.getItem("reservation-language");if(saved==="ko"||saved==="en"||saved==="vi")setLang(saved)}catch{}},[]);
 function changeLanguage(value:Lang){setLang(value);try{localStorage.setItem("reservation-language",value)}catch{}document.documentElement.lang=value;}
 useEffect(()=>{try{const saved=localStorage.getItem("reservation-theme");if(saved==="dark"||saved==="light")setTheme(saved)}catch{}},[]);
 useEffect(()=>{if(!db)return;const load=async()=>{const {data}=await db!.from("reservation_brand_settings").select("room_name,subtitle,logo_url,default_theme").eq("id",true).maybeSingle();if(data){setBrand(data as Brand);if(!localStorage.getItem("reservation-theme"))setTheme(data.default_theme)}};void load()},[]);
 function changeTheme(next:"dark"|"light"){setTheme(next);try{localStorage.setItem("reservation-theme",next)}catch{}}
 const loadPublic=useCallback(async()=>{if(!db)return;const [g,st]=await Promise.all([db.from("reservation_games").select("*").order("starts_at",{ascending:true}).gte("starts_at",new Date(Date.now()-36*3600000).toISOString()),db.rpc("reservation_public_stats")]);
 const room=await db.rpc("reservation_live_room_status");if(!room.error)setRunning5m(Number(room.data?.[0]?.running_5m||0));if(g.error)notice(g.error.message);else setGames(g.data||[]);if(st.error)notice(st.error.message);else setStats((st.data||[]).map((r:any)=>({...r,confirmed_count:Number(r.confirmed_count),pending_count:Number(r.pending_count),waiting_count:Number(r.waiting_count)})));setLoading(false)},[]);
 const loadMine=useCallback(async(ts:string[])=>{const client=db;if(!client||!ts.length){setMine([]);return}const results=await Promise.all(ts.slice(0,30).map(async token=>{const {data}=await client.rpc("lookup_poker_reservation",{p_token:token});return data?.[0]?{...data[0],id:data[0].reservation_id||data[0].id||token,lookup_token:token}:null}));setMine(results.filter(Boolean) as Own[])},[]);
 const loadStaff=useCallback(async()=>{if(!db)return;const {data,error}=await db.from("reservations").select("id,game_id,player_name,arrival_at,status,created_at,member_number,guest_note").order("created_at",{ascending:false}).limit(500);if(!error){setBookings(data||[]);setBookingsLoaded(true)}const a=await db.from("reservation_audit").select("*").order("created_at",{ascending:false}).limit(100);if(!a.error)setAudit(a.data||[])},[]);
 useEffect(()=>{try{const list=JSON.parse(localStorage.getItem(TOKEN_KEY)||"[]");if(Array.isArray(list))setTokens(list.filter((x:any)=>typeof x==="string"))}catch{}},[]);
 useEffect(()=>{if(configured)void loadPublic();else setLoading(false);},[loadPublic]);
 useEffect(()=>{if(db)void loadMine(tokens)},[tokens,loadMine]);
 useEffect(()=>{if(!db)return;const client=db;let live=true;const check=async()=>{const s=await client.auth.getUser();if(!live)return;const u=s.data.user;if(!u){setProfile(null);setSessionUser("");return}setSessionUser(u.id);const p=await client.from("user_profiles").select("role,display_name,active").eq("user_id",u.id).maybeSingle();if(live)setProfile(p.data as Profile|null)};void check();const {data:{subscription}}=client.auth.onAuthStateChange(()=>{void check()});return()=>{live=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{if(!staff)return;void loadStaff()},[staff,loadStaff]);
 useEffect(()=>{if(!configured)return;const timer=setInterval(()=>{void loadPublic();void loadMine(tokens);if(staff)void loadStaff()},9000);const focus=()=>{void loadPublic();void loadMine(tokens);if(staff)void loadStaff()};window.addEventListener("focus",focus);return()=>{clearInterval(timer);window.removeEventListener("focus",focus)}},[staff,tokens,loadPublic,loadMine,loadStaff]);
 
 async function notifyTelegram(token:string){try{const response=await fetch("/api/notify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token}),cache:"no-store"});if(!response.ok){const data=await response.json().catch(()=>({}));notice((lang==="ko"?"예약은 접수됐지만 텔레그램 알림 전송에 실패했습니다. 관리자에게 알려주세요. ":lang==="vi"?"Đã nhận đặt chỗ nhưng gửi Telegram thất bại. ":"Booking saved, but Telegram notification failed. ")+(data.error||""));return false}return true}catch{notice(lang==="ko"?"예약은 접수됐지만 텔레그램 연결에 실패했습니다.":"Booking saved, but Telegram connection failed.");return false}}
 async function requestBooking(){if(!db||!selectedGame)return;if(name.trim().length<2){notice("이름을 2글자 이상 입력해주세요.");return}setBusy(true);const {data,error}=await db.rpc("request_poker_reservation",{p_game:selectedGame.id,p_name:name.trim(),p_arrival:new Date(arrival+"+07:00").toISOString(),p_note:guestNote});setBusy(false);if(error){notice(error.message);return}const token=data?.[0]?.reservation_token;if(token){const next=[String(token),...tokens].slice(0,30);setTokens(next);localStorage.setItem(TOKEN_KEY,JSON.stringify(next));notice(t.request);setGuestNote("");void notifyTelegram(String(token));void loadMine(next);void loadPublic()}}
 async function cancelBooking(token:string){if(!db||!confirm(t.confirmCancel))return;setBusy(true);const {data,error}=await db.rpc("cancel_poker_reservation",{p_token:token});setBusy(false);notice(error?.message||(!data?"Cannot cancel this booking":"Cancelled"));void loadMine(tokens);void loadPublic()}
 async function login(){if(!db)return;setBusy(true);let authEmail=email.trim().toLowerCase();if(!authEmail.includes("@")){const r=await db.rpc("resolve_login_email",{p_username:authEmail});if(r.error||typeof r.data!=="string"||!r.data){notice(r.error?.message||"계정을 찾을 수 없습니다.");setBusy(false);return}authEmail=r.data}const {error}=await db.auth.signInWithPassword({email:authEmail,password});setBusy(false);notice(error?.message||"");}
 async function logout(){await db?.auth.signOut();setProfile(null);setSessionUser("");setView("guest")}
 async function manage(id:string,status:Status){if(!db)return;setBusy(true);const {error}=await db.rpc("manage_poker_reservation",{p_id:id,p_status:status});setBusy(false);if(error)notice(error.message);else{notice("Saved");void loadStaff();void loadPublic();}}
 async function createGame(){if(!db)return;setBusy(true);const {error}=await db.rpc("manage_reservation_game",{p_id:null,p_title:newGame.title.trim(),p_table_no:newGame.table_no.trim(),p_game_no:newGame.game_no.trim(),p_starts_at:new Date(newGame.starts+"+07:00").toISOString(),p_capacity:Number(newGame.capacity),p_open:true});setBusy(false);notice(error?.message||"다음 게임 예약이 열렸습니다.");if(!error)void loadPublic()}
 async function setOpen(game:Game,is_open:boolean){if(!db)return;setBusy(true);const {error}=await db.rpc("manage_reservation_game",{p_id:game.id,p_title:game.title,p_table_no:game.table_no,p_game_no:game.game_no||"1",p_starts_at:game.starts_at,p_capacity:game.capacity,p_open:is_open});setBusy(false);notice(error?.message||(is_open?"예약을 열었습니다.":"예약 접수를 닫았습니다."));void loadPublic()}
 const bookByGame=useMemo(()=>bookings.filter(b=>filter==="all"||b.game_id===filter),[bookings,filter]);
 return <main className={"shell bookingTheme "+(theme==="light"?"themeLight":"themeDark")}><header className="header"><div className="brand"><img className="brandLogo" src={brand.logo_url} alt={brand.room_name+" logo"}/><div><strong>{brand.room_name}</strong><small>{brand.subtitle}</small></div></div><div className="bookingHeaderActions"><button aria-label="테마 변경" onClick={()=>changeTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?"☀ 라이트":"☾ 다크"}</button><select aria-label="Language" value={lang} onChange={e=>changeLanguage(e.target.value as Lang)}><option value="ko">한국어</option><option value="en">English</option><option value="vi">Tiếng Việt</option></select></div></header>
 {!configured&&<div className="warning">{t.demo} · NEXT_PUBLIC_SUPABASE_ANON_KEY</div>}
 
 {message&&<div className="alert" role="status" onClick={()=>setMessage("")}>{message} <span>×</span></div>}
 {!staffOnly?<><section className="hero"><h1>{t.home}</h1></section><section className="panel"><div className="sectionHead"><h2>{t.select}</h2><span className="hint">{t.capacityHint}</span></div><div className="roomStatus">{running5m===null?"":lang==="vi"?`Hiện có ${running5m} bàn 5M đang chạy`:lang==="en"?`${running5m} 5M tables running`:`현재 5M ${running5m}테이블 진행 중`}</div><div className="gameList">{loading?<p>Loading…</p>:!activeGames.length?<div className="gameEmpty"><strong>5M TIME ATTACK</strong><span>{lang==="vi"?"Đang chuẩn bị lịch mở bàn":lang==="en"?"Schedule being prepared":"시작 예정 시간 확인 중"}</span><small>{lang==="vi"?"Chưa nhận đặt chỗ · nhân viên sẽ mở lịch sớm":lang==="en"?"Bookings open when the cashier confirms the schedule":"아직 예약 접수 전입니다. 운영자가 시작 시간과 좌석을 등록하면 이곳에 표시됩니다."}</small></div>:activeGames.map(g=>{const st=stats.find(x=>x.game_id===g.id);const free=Math.max(0,g.capacity-(st?.confirmed_count||0));return <button key={g.id} className={"gameCard "+(selected===g.id?"active":"")} onClick={()=>{setSelected(g.id);setArrival(localDatetime(new Date(Math.max(Date.now()+1800000,new Date(g.starts_at).getTime()))))}}><div><strong>{g.title}</strong><span className="gameStart">{lang==="vi"?"Bắt đầu dự kiến":lang==="en"?"Estimated start":"시작 예정"} · {fmt(g.starts_at,lang)}</span><small> {g.table_no?"· TABLE "+g.table_no:""}{g.game_no?" · No."+g.game_no:""}</small><small>{g.description}</small></div><div className="gameNumbers"><b className={free?"green":"gold"}>{free} {lang==="vi"?"chỗ":lang==="en"?"seats":"자리 남음"}</b><small>{lang==="vi"?"Tổng "+g.capacity+" chỗ":lang==="en"?"Total "+g.capacity+" seats":"전체 "+g.capacity+"석"} · {st?.confirmed_count||0} {t.seats}</small><small>{free?t.available:t.full}</small><small>{st?.pending_count||0} {t.pending}</small></div></button>})}</div></section>
 <section className="panel"><h2>{t.book}</h2><p className="muted">{t.help}</p><div className="reservationModes"><button type="button" className={!memberMode?"selected":""} onClick={()=>setMemberMode(false)}>{lang==="vi"?"Đặt chỗ không cần tài khoản":lang==="en"?"Guest booking":"비회원 예약"}</button><button type="button" className={memberMode?"selected":""} onClick={()=>setMemberMode(true)}>{lang==="vi"?"Đặt bằng hồ sơ đã lưu":lang==="en"?"Saved member booking":"회원 간편 예약"}</button></div><label className="guestNoteLabel">{lang==="vi"?"Ghi chú / Yêu cầu đặc biệt":lang==="en"?"Notes / Special requests":"메모 · 특이사항 (선택)"}<textarea rows={3} maxLength={500} value={guestNote} onChange={e=>setGuestNote(e.target.value)} placeholder={lang==="vi"?"Ví dụ: Đến muộn 10 phút":lang==="en"?"e.g. Arriving 10 minutes late":"예: 이전 게임 종료 후 이동 / 10분 늦게 도착"}/></label>{memberMode?<><label className="sharedArrival">{t.arrival}<input type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></label><MemberBooking language={lang} gameId={selected} arrival={arrival} note={guestNote} onBooked={token=>{const next=[token,...tokens.filter(x=>x!==token)].slice(0,30);setTokens(next);localStorage.setItem(TOKEN_KEY,JSON.stringify(next));void notifyTelegram(token);void loadMine(next);void loadPublic()}}/></>:<div className="bookingForm"><label>{t.name}<input autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="NAME / 이름 / Tên"/></label><label>{t.arrival}<input type="datetime-local" value={arrival} onChange={e=>setArrival(e.target.value)}/></label><button className="primary" disabled={!configured||!selected||busy} onClick={()=>void requestBooking()}>{busy?"…":t.book} →</button></div>}</section>
 <section className="panel"><h2>{t.mine}</h2>{mine.length?mine.map((b,i)=><div className="bookingRow" key={b.id}><div><strong>{b.game_title}</strong><small>{fmt(b.arrival_at,lang)} · {b.player_name}</small><small>#{String(b.id||b.lookup_token||"").slice(0,8)}</small></div><div className="bookingRight"><span className={"status "+b.status}>{t[b.status]}</span>{["pending","confirmed","waitlisted"].includes(b.status)&&<button className="quiet" disabled={busy} onClick={()=>void cancelBooking(b.lookup_token||"")}>{t.cancel}</button>}</div></div>):<p className="muted">{t.empty}</p>}</section></>:
 !sessionUser?<section className="panel login"><h1>{t.login}</h1><label>{t.id}<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username"/></label><label>{t.password}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary" disabled={busy||!configured} onClick={()=>void login()}>{t.signIn}</button></section>:
 !staff?<section className="panel"><p>{t.access}</p><button onClick={()=>void logout()}>{t.signOut}</button></section>:
 <>{profile?.role==="admin"&&<details className="brandSettingsDisclosure"><summary>{lang==="en"?"⚙ Room logo, name & appearance":lang==="vi"?"⚙ Logo, tên phòng & giao diện":"⚙ 포커룸 로고 · 이름 · 기본 테마 설정"}</summary><BrandSettings lang={lang} value={brand} onSaved={b=>{setBrand(b);changeTheme(b.default_theme)}}/></details>}<StaffDashboard lang={lang} games={games} bookings={bookings} bookingsLoaded={bookingsLoaded} stats={stats} running={running5m} profileName={profile?.display_name||profile?.role||"Staff"} admin={profile?.role==="admin"} busy={busy} onLogout={()=>void logout()} onRefresh={()=>{void loadStaff();void loadPublic()}} onManage={(id,status)=>void manage(id,status)} onCreate={()=>void createGame()} onToggle={(g,opened)=>void setOpen(g,opened)} newGame={newGame} setNewGame={setNewGame} sound={sound} setSound={setSound} audit={audit}/></>}
 <footer>© DREAM POKER DA NANG · Reservations</footer></main>
}
