"use client";
import {useEffect,useRef,useState} from "react";
type Booking={id:string;game_id:string;player_name:string;status:string;created_at:string};
type Game={id:string;table_no:string;game_no?:string;title:string};
type Setting={enabled:boolean;mode:"voice"|"bell"|"double"|"soft";voice:string;volume:number;rate:number};
const KEY="dream-reservation-audio-v2";
const defaults:Setting={enabled:false,mode:"voice",voice:"",volume:0.75,rate:1};
export default function ReservationAlerts({bookings,games}:{bookings:Booking[];games:Game[]}){
 const [setting,setSetting]=useState<Setting>(defaults);
 const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 const [open,setOpen]=useState(false),[toast,setToast]=useState("");
 const ready=useRef(false),seen=useRef<Set<string>>(new Set()),ctx=useRef<AudioContext|null>(null),settingsRef=useRef(setting),gamesRef=useRef(games);
 useEffect(()=>{settingsRef.current=setting;gamesRef.current=games;try{localStorage.setItem(KEY,JSON.stringify(setting))}catch{}},[setting,games]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved&&typeof saved==="object")setSetting({...defaults,...saved,enabled:false})}catch{}const load=()=>setVoices(window.speechSynthesis?.getVoices()||[]);load();window.speechSynthesis?.addEventListener?.("voiceschanged",load);return()=>window.speechSynthesis?.removeEventListener?.("voiceschanged",load)},[]);
 function alertFor(b:Booking){const g=gamesRef.current.find(x=>x.id===b.game_id);const target=g?.table_no?`${g.table_no}번 테이블`:"다음";const no=g?.game_no?` ${g.game_no}번 게임`:" 게임";return `${b.player_name}님께서 ${target}의${no}을 예약하셨습니다.`;}
 function bell(mode:Setting["mode"],volume:number){try{const audio=ctx.current||new AudioContext();ctx.current=audio;void audio.resume();const t=audio.currentTime;const frequencies=mode==="double"?[660,880,660]:mode==="soft"?[523,659,784]:[880,1046];frequencies.forEach((freq,i)=>{const oscillator=audio.createOscillator(),gain=audio.createGain();const at=t+i*0.17;oscillator.type=mode==="soft"?"sine":"triangle";oscillator.frequency.value=freq;gain.gain.setValueAtTime(0.0001,at);gain.gain.exponentialRampToValueAtTime(Math.max(0.001,volume*0.15),at+0.025);gain.gain.exponentialRampToValueAtTime(0.0001,at+0.14);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(at);oscillator.stop(at+0.16)})}catch{}}
 function play(text:string,current:Setting){if(current.mode!=="voice"){bell(current.mode,current.volume);return;}if(!("speechSynthesis" in window)){bell("double",current.volume);return;}const utterance=new SpeechSynthesisUtterance(text);const options=window.speechSynthesis.getVoices();utterance.voice=options.find(v=>v.voiceURI===current.voice)||options.find(v=>v.lang.toLowerCase().startsWith("ko"))||null;utterance.lang=utterance.voice?.lang||"ko-KR";utterance.rate=current.rate;utterance.volume=current.volume;window.speechSynthesis.cancel();window.speechSynthesis.speak(utterance);}
 useEffect(()=>{const current=bookings.filter(b=>b.status==="pending");if(!ready.current){seen.current=new Set(bookings.map(b=>b.id));ready.current=true;return;}const fresh=current.filter(b=>!seen.current.has(b.id));bookings.forEach(b=>seen.current.add(b.id));if(!fresh.length)return;const item=fresh[0];const text=alertFor(item);setToast(fresh.length>1?`${text} 외 ${fresh.length-1}건의 새 예약`:text);if(settingsRef.current.enabled){if(fresh.length>1)play(`새 예약 ${fresh.length}건이 접수되었습니다. ${text}`,settingsRef.current);else play(text,settingsRef.current)}},[bookings]);
 function enable(){const updated={...setting,enabled:!setting.enabled};setSetting(updated);if(!setting.enabled){bell("soft",updated.volume);setOpen(true)}else window.speechSynthesis?.cancel();}
 const korean=voices.filter(v=>v.lang.toLowerCase().startsWith("ko"));const voiceOptions=korean.length?korean:voices;
 return <><div className="notifyControl"><button className={setting.enabled?"notifyEnabled":""} onClick={enable}>{setting.enabled?"🔊 음성 알림 ON":"🔕 알림 켜기"}</button><button onClick={()=>setOpen(v=>!v)} title="알림음 및 목소리 설정">⚙ 설정</button></div>
 {toast&&<div className="bookingToast" role="status"><strong>♠ 신규 예약 접수</strong><p>{toast}</p><button onClick={()=>setToast("")}>닫기</button></div>}
 {open&&<div className="notificationSettings"><div className="notificationTitle"><strong>예약 알림 설정</strong><button onClick={()=>setOpen(false)}>닫기 ×</button></div><label>알림 방식<select value={setting.mode} onChange={e=>setSetting({...setting,mode:e.target.value as Setting["mode"]})}><option value="voice">한국어 음성 안내</option><option value="bell">밝은 호출음</option><option value="double">긴급 3회 벨</option><option value="soft">부드러운 차임</option></select></label>{setting.mode==="voice"&&<><label>목소리<select value={setting.voice} onChange={e=>setSetting({...setting,voice:e.target.value})}><option value="">기본 한국어 목소리</option>{voiceOptions.map(v=><option value={v.voiceURI} key={v.voiceURI}>{v.name} ({v.lang})</option>)}</select></label><label>말하기 속도 <span>{setting.rate.toFixed(1)}배</span><input type="range" min="0.7" max="1.3" step="0.1" value={setting.rate} onChange={e=>setSetting({...setting,rate:Number(e.target.value)})}/></label></>}<label>음량 <span>{Math.round(setting.volume*100)}%</span><input type="range" min="0.1" max="1" step="0.1" value={setting.volume} onChange={e=>setSetting({...setting,volume:Number(e.target.value)})}/></label><button className="notificationPreview" onClick={()=>play("김지원님께서 5번 테이블의 다음 게임을 예약하셨습니다.",setting)}>▶ 알림 미리 듣기</button><small>PC에서 직원 화면을 열어둔 동안 동작합니다. 사용자가 알림을 켜야 소리가 재생되며, 목소리는 기기에 설치된 음성을 사용합니다.</small></div>}</>;
}
