"use client";
import {useMemo,useState} from "react";
import DeskTools from "./DeskTools";
import TelegramSetup from "./TelegramSetup";
import ReservationAlerts from "./ReservationAlerts";
type Game={id:string;title:string;starts_at:string;capacity:number;is_open:boolean;table_no:string;game_no?:string;description:string};
type Booking={id:string;game_id:string;player_name:string;arrival_at:string;status:string;created_at:string;member_number?:string|null;guest_note?:string|null};
type Stat={game_id:string;confirmed_count:number;pending_count:number;waiting_count:number};
type Form={title:string;starts:string;capacity:string;table_no:string;game_no:string;description:string};
const labels:Record<string,string>={confirmed:"예약 확정",waitlisted:"대기 등록",rejected:"거절",checked_in:"입장 완료",no_show:"노쇼",cancelled:"취소",pending:"승인 대기"};
const format=(value:string)=>new Date(value).toLocaleString("ko-KR",{timeZone:"Asia/Ho_Chi_Minh",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"});
export default function StaffDashboard({games,bookings,stats,running,profileName,admin,busy,onLogout,onRefresh,onManage,onCreate,onToggle,newGame,setNewGame,sound,setSound,audit}:{games:Game[];bookings:Booking[];stats:Stat[];running:number|null;profileName:string;admin:boolean;busy:boolean;onLogout:()=>void;onRefresh:()=>void;onManage:(id:string,status:any)=>void;onCreate:()=>void;onToggle:(g:Game,opened:boolean)=>void;newGame:Form;setNewGame:(f:Form)=>void;sound:boolean;setSound:(v:boolean)=>void;audit:Array<{id:number;reservation_id:string;previous_status:string|null;new_status:string;created_at:string}>}){
 const [selectedGame,setSelectedGame]=useState("all"),[selectedBooking,setSelectedBooking]=useState(""),[mobileTab,setMobileTab]=useState<"games"|"list"|"detail">("list"),[tools,setTools]=useState<"desk"|"telegram"|"audit"|null>(null),[query,setQuery]=useState("");
 const shown=useMemo(()=>bookings.filter(b=>(selectedGame==="all"||b.game_id===selectedGame)&&(!query||[b.player_name,b.member_number||"",b.guest_note||""].join(" ").toLowerCase().includes(query.toLowerCase()))),[bookings,selectedGame,query]);
 const current=shown.find(b=>b.id===selectedBooking)||shown[0];
 const pending=bookings.filter(b=>b.status==="pending").length;
 const confirmed=bookings.filter(b=>b.status==="confirmed"||b.status==="checked_in").length;
 const open=games.filter(g=>g.is_open);
 const activeGame=games.find(g=>g.id===selectedGame);
 const gameCount=(id:string,status:string)=>bookings.filter(b=>b.game_id===id&&b.status===status).length;
 const gameLabel=(g:Game)=>`Table ${g.table_no||"?"} · No.${g.game_no||"?"}`;
 return <div className="staffWorkspace"><div className="staffTop"><div><strong>예약 관리</strong><small>{profileName} · Dream Poker</small></div><div className="staffKpis"><span>진행 <b>{running??"—"}</b></span><span>예약 오픈 <b>{open.length}</b></span><span>승인 대기 <b className="staffGold">{pending}</b></span><span>확정 <b>{confirmed}</b></span></div><div className="staffTopActions"><ReservationAlerts bookings={bookings} games={games}/><a className="staffGuestLink" href="/" target="_blank" rel="noopener noreferrer">손님 화면 ↗</a><button onClick={onRefresh}>새로고침</button><button onClick={onLogout}>로그아웃</button></div></div>
 <div className="staffMobileNav"><button className={mobileTab==="games"?"on":""} onClick={()=>setMobileTab("games")}>예약창</button><button className={mobileTab==="list"?"on":""} onClick={()=>setMobileTab("list")}>예약자 {pending? `(${pending})`:""}</button><button className={mobileTab==="detail"?"on":""} onClick={()=>setMobileTab("detail")}>상세 처리</button></div>
 <div className="staffGrid">
 <aside className={`staffPane staffGames ${mobileTab==="games"?"mobileOn":""}`}><div className="staffPaneHead"><h2>예약창 관리</h2><small>다음 게임 대기 접수</small></div><div className="staffScroll">
 <div className="staffCreate"><div className="staffSubheading">+ 다음 게임 예약 열기</div><div className="staffCreateGrid"><label>테이블<input value={newGame.table_no} onChange={e=>setNewGame({...newGame,table_no:e.target.value})}/></label><label>게임 No.<input value={newGame.game_no} onChange={e=>setNewGame({...newGame,game_no:e.target.value})}/></label><label className="wide">게임명<input value={newGame.title} onChange={e=>setNewGame({...newGame,title:e.target.value})}/></label><label className="wide">시작 예정<input type="datetime-local" value={newGame.starts} onChange={e=>setNewGame({...newGame,starts:e.target.value})}/></label><label>좌석 정원<input type="number" min="1" max="30" value={newGame.capacity} onChange={e=>setNewGame({...newGame,capacity:e.target.value})}/></label></div><button className="staffAdd" disabled={busy||!newGame.table_no.trim()||!newGame.game_no.trim()||!newGame.title.trim()} onClick={onCreate}>예약창 열기 +</button></div>
 <div className="staffSubheading">예약 게임 목록</div><button className={`staffGameOption ${selectedGame==="all"?"active":""}`} onClick={()=>{setSelectedGame("all");setMobileTab("list")}}><strong>전체 게임</strong><span>{bookings.length}건 · 대기 {pending}</span></button>
 {games.map(g=>{const st=stats.find(x=>x.game_id===g.id);return <div className={`staffGameOption ${selectedGame===g.id?"active":""}`} key={g.id}><button className="staffGameChoose" onClick={()=>{setSelectedGame(g.id);setSelectedBooking("");setMobileTab("list")}}><strong>{gameLabel(g)}</strong><small>{g.title} · {format(g.starts_at)}</small><span>확정 {st?.confirmed_count??gameCount(g.id,"confirmed")}/{g.capacity} · 승인 대기 {st?.pending_count??gameCount(g.id,"pending")}</span></button><button className={`staffQueueToggle ${g.is_open?"open":""}`} disabled={busy} onClick={()=>onToggle(g,!g.is_open)}>{g.is_open?"예약 닫기":"예약 열기"}</button></div>})}
 </div></aside>
 <section className={`staffPane staffList ${mobileTab==="list"?"mobileOn":""}`}><div className="staffPaneHead"><h2>{activeGame?gameLabel(activeGame):"전체 예약자"}</h2><small>{activeGame?`${activeGame.title} · ${format(activeGame.starts_at)}`:"예약자 클릭 후 오른쪽에서 처리"}</small></div><div className="staffListTools"><input placeholder="이름 · 회원번호 · 메모 검색" value={query} onChange={e=>setQuery(e.target.value)}/><span>{shown.length}명</span></div><div className="staffScroll staffTableScroll"><table className="staffTable"><thead><tr><th>상태</th><th>예약자</th><th>회원번호</th><th>도착 예정</th><th>게임</th></tr></thead><tbody>{shown.map(b=><tr key={b.id} className={current?.id===b.id?"selected":""} onClick={()=>{setSelectedBooking(b.id);setMobileTab("detail")}}><td><span className={`staffStatus ${b.status}`}>{labels[b.status]||b.status}</span></td><td><strong>{b.player_name}</strong>{b.guest_note&&<small title={b.guest_note}>📝 {b.guest_note}</small>}</td><td>{b.member_number?<b className="staffMemberId">{b.member_number}</b>:"—"}</td><td>{format(b.arrival_at)}</td><td>{games.find(g=>g.id===b.game_id)?.table_no||"—"} / {games.find(g=>g.id===b.game_id)?.game_no||"—"}</td></tr>)}</tbody></table>{!shown.length&&<div className="staffEmpty">표시할 예약자가 없습니다.</div>}</div></section>
 <aside className={`staffPane staffDetail ${mobileTab==="detail"?"mobileOn":""}`}><div className="staffPaneHead"><h2>예약 상세 · 빠른 처리</h2><small>예약을 선택하세요</small></div><div className="staffScroll">{current?<><div className="staffPerson"><strong>{current.player_name}</strong><span className={`staffStatus ${current.status}`}>{labels[current.status]||current.status}</span></div>{current.member_number&&<div className="staffIdCard">회원 ID <b>{current.member_number}</b></div>}<dl className="staffFacts"><div><dt>게임</dt><dd>{games.find(g=>g.id===current.game_id)?.title||"—"}</dd></div><div><dt>테이블 / No.</dt><dd>{games.find(g=>g.id===current.game_id)?.table_no||"—"} / {games.find(g=>g.id===current.game_id)?.game_no||"—"}</dd></div><div><dt>도착 예정</dt><dd>{format(current.arrival_at)}</dd></div><div><dt>신청 시각</dt><dd>{format(current.created_at)}</dd></div></dl><div className="staffNote"><small>특이사항</small><p>{current.guest_note||"없음"}</p></div><div className="staffActionGrid"><button className="confirm" disabled={busy||current.status==="confirmed"} onClick={()=>onManage(current.id,"confirmed")}>예약 확정</button><button className="wait" disabled={busy||current.status==="waitlisted"} onClick={()=>onManage(current.id,"waitlisted")}>대기 등록</button><button className="reject" disabled={busy||current.status==="rejected"} onClick={()=>onManage(current.id,"rejected")}>거절</button><button disabled={busy||current.status==="checked_in"} onClick={()=>onManage(current.id,"checked_in")}>입장 완료</button><button disabled={busy||current.status==="no_show"} onClick={()=>onManage(current.id,"no_show")}>노쇼</button><button disabled={busy||current.status==="cancelled"} onClick={()=>onManage(current.id,"cancelled")}>취소</button></div></>:<div className="staffEmpty">왼쪽 예약자 명단에서 선택하세요.</div>}
 <div className="staffTools"><h3>현장 도구</h3><div className="staffToolBtns"><button onClick={()=>setTools(tools==="desk"?null:"desk")}>현장 예약 · 채팅</button>{admin&&<button onClick={()=>setTools(tools==="telegram"?null:"telegram")}>텔레그램 설정</button>}<button onClick={()=>setTools(tools==="audit"?null:"audit")}>변경 이력</button></div></div></div></aside>
 </div>
 {tools&&<div className="staffOverlay" role="presentation" onClick={()=>setTools(null)}><div className="staffDrawer" role="dialog" aria-modal="true" aria-label="현장 도구" onClick={e=>e.stopPropagation()}><div className="staffDrawerTop"><strong>{tools==="desk"?"현장 예약 · 캐셔 채팅":tools==="telegram"?"텔레그램 연결":"변경 이력"}</strong><button onClick={()=>setTools(null)}>닫기 ×</button></div>{tools==="desk"?<DeskTools games={games} bookings={bookings} language="ko" refresh={onRefresh}/>:tools==="telegram"?<TelegramSetup/>:<div className="staffAudit">{audit.map(a=><div key={a.id}>{a.reservation_id.slice(0,8)} · {a.previous_status||"new"} → {a.new_status}<small>{format(a.created_at)}</small></div>)}</div>}</div></div>}
 </div>;
}
